# Generated by Django 4.0.1 on 2022-02-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('pop', 'POP'), ('blues', 'Blues'), ('rap', 'Rap'), ('afro_beat', 'Afro beat'), ('gospel', 'Gospel')], max_length=355)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
